version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - app_network
    ports:
      - "127.0.0.1:8080:8080"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DB_CONNECTION: '${DB_CONNECTION:-pgsql}'
      DB_HOST: '${DB_HOST:-db}'
      DB_DATABASE: '${DB_DATABASE:-application}'
      DB_PORT: '${DB_PORT:-5432}'
      DB_USERNAME: '${DB_USERNAME:-user}'
      DB_PASSWORD: '${DB_PASSWORD:-password}'
      OCTANE_HTTPS: '${OCTANE_HTTPS:-false}'
      LOG_CHANNEL: '${LOG_CHANNEL:-stderr}'
      SENTRY_LARAVEL_DSN: '${SENTRY_LARAVEL_DSN}'
      KAFKA_BROKER_LIST: '${KAFKA_BROKER_LIST:-host.docker.internal:9092}'
      KAFKA_SASL_USERNAME: '${KAFKA_SASL_USERNAME:-user}'
      KAFKA_SASL_PASSWORD: '${KAFKA_SASL_PASSWORD:-password}'

  db:
    image: postgres:15.1
    container_name: db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: '${DB_DATABASE:-application}'
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
