# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - db
  db:
    image: postgres:15.1
    container_name: db
    ports:
      - "3306:3306"
    environment:
      POSTGRES_DB: '${DB_DATABASE:-application}'
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    networks:
      - sail
    volumes:
      - sail_db:/var/lib/mysql
networks:
  sail:
    driver: bridge
volumes:
  sail_db:
    driver: local
